version: '3.8'
services:
  best-email-service:
    build: .
    command: ["npm", "run", "start:dev"]
    env_file: .env
    depends_on:
      - redis
    ports:
      - '3003:3003'
    volumes:
      - ./:/app
      - ./templates:/templates
      - /app/node_modules
    networks:
      - my-network

  redis:
    image: redis:alpine
    command: /bin/sh -c "redis-server"
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

networks:
  my-network:
    driver: bridge
